version: '2'

services:
  tao:
    build: https://github.com/mrft/docker-tao.git
    ### while fiddling with docker repo I'm using the local version: 
    #build: ../docker-tao
    ### the original version pointed to a container published on docker 
    #image: alroniks/tao
    restart: always
    volumes:
      - ./docker_volumes/tao/var_www_html:/var/www/html
    links:
      - postgres
  web:
    image: nginx
    restart: always
    ports:
      - "${NGINX_PORT}:80"
    volumes_from:
      - tao
    volumes:
      - ./docker_volumes/web/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - tao

  postgres:
     image: postgres:9.6
     restart: always
     environment:
       POSTGRES_PASSWORD: "${PROJECT_NAME}"

#  dbs:
#    image: mysql
#    restart: always
#    ports:
#      - "${MYSQL_PORT}:3306"
#    volumes:
#      - data:/var/lib/mysql:rw
#    environment:
#      MYSQL_ROOT_PASSWORD: "${PROJECT_NAME}"
#      MYSQL_USER: "${PROJECT_NAME}"
#      MYSQL_PASSWORD: "${PROJECT_NAME}"
#      MYSQL_DATABASE: "${PROJECT_NAME}"

volumes:
  data:
    driver: local
